name: deploy-manifests

on:
  push:
    branches: ['main']
    paths:
      - 'infra/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Configure Kubernetes with proper file handling
      - name: Configure Kubernetes
        run: |
          mkdir -p ~/.kube
          # Clean and properly format the kubeconfig
          echo "$KUBE_CONFIG" | base64 -d > ~/.kube/config
          chmod 600 ~/.kube/config
          # Verify the config
          kubectl config view
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}

      # Deploy to Kubernetes
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f infra/k8s
