name: deploy-client

on:
  push:
    branches: ['main']
    paths:
      - 'client/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: cd client && docker build -t arigatory/client:new-tag .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push arigatory/client:new-tag

      # Configure Kubernetes with proper file handling
      - name: Configure Kubernetes
        run: |
          mkdir -p ~/.kube
          # Clean and properly format the kubeconfig
          echo "$KUBE_CONFIG" | base64 -d > ~/.kube/config
          chmod 600 ~/.kube/config
          # Verify the config
          kubectl config view
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}

      # Deploy to Kubernetes
      - name: Deploy to Kubernetes
        run: |
          kubectl rollout restart deployment client-depl
