name: deploy-auth

on:
  push:
    branches: [ "main" ]
    paths:
      - 'auth/**'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: cd auth && docker build -t arigatory/auth .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push arigatory/auth
          

      # Add kubectl apply step
      - name: Deploy to Kubernetes
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" > kubeconfig.yaml
          export KUBECONFIG=kubeconfig.yaml
          kubectl rollout restart deployment auth-depl
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}